<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 7,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            9 => 
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => 11,
            ),
            10 => 
            array (
                'id' => 12,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 12,
            ),
            11 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            12 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            13 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            14 => 
            array (
                'id' => 16,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            15 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            16 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            17 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            18 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            19 => 
            array (
                'id' => 21,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            20 => 
            array (
                'id' => 22,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            21 => 
            array (
                'id' => 23,
                'data_type_id' => 1,
                'field' => 'about',
                'type' => 'text_area',
                'display_name' => 'About',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 11,
            ),
            22 => 
            array (
                'id' => 24,
                'data_type_id' => 4,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Nº',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 1,
            ),
            23 => 
            array (
                'id' => 25,
                'data_type_id' => 4,
                'field' => 'nome',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            24 => 
            array (
                'id' => 26,
                'data_type_id' => 4,
                'field' => 'curso',
                'type' => 'text',
                'display_name' => 'Curso',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            25 => 
            array (
                'id' => 27,
                'data_type_id' => 4,
                'field' => 'atualizacao_nome',
                'type' => 'checkbox',
                'display_name' => 'Atualizacao Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Atualizado","off":"Não atualizado","checked":"true"}',
                'order' => 4,
            ),
            26 => 
            array (
                'id' => 28,
                'data_type_id' => 4,
                'field' => 'siga',
                'type' => 'checkbox',
                'display_name' => 'Siga',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Atualizado","off":"Não atualizado","checked":"true"}',
                'order' => 5,
            ),
            27 => 
            array (
                'id' => 29,
                'data_type_id' => 4,
                'field' => 'sistec',
                'type' => 'checkbox',
                'display_name' => 'Sistec',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Atualizado","off":"Não atualizado","checked":"true"}',
                'order' => 6,
            ),
            28 => 
            array (
                'id' => 30,
                'data_type_id' => 4,
                'field' => 'observacao',
                'type' => 'text',
                'display_name' => 'Observacao',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 7,
            ),
            29 => 
            array (
                'id' => 31,
                'data_type_id' => 5,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            30 => 
            array (
                'id' => 32,
                'data_type_id' => 5,
                'field' => 'user_id',
                'type' => 'number',
                'display_name' => 'User Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            31 => 
            array (
                'id' => 33,
                'data_type_id' => 5,
                'field' => 'mensagem',
                'type' => 'text',
                'display_name' => 'Mensagem',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            32 => 
            array (
                'id' => 34,
                'data_type_id' => 5,
                'field' => 'to',
                'type' => 'number',
                'display_name' => 'To',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            33 => 
            array (
                'id' => 35,
                'data_type_id' => 5,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            34 => 
            array (
                'id' => 36,
                'data_type_id' => 5,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            35 => 
            array (
                'id' => 37,
                'data_type_id' => 5,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 7,
            ),
            36 => 
            array (
                'id' => 38,
                'data_type_id' => 5,
                'field' => 'titulo',
                'type' => 'text',
                'display_name' => 'Titulo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            37 => 
            array (
                'id' => 39,
                'data_type_id' => 5,
                'field' => 'read',
                'type' => 'text',
                'display_name' => 'Read',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            38 => 
            array (
                'id' => 40,
                'data_type_id' => 6,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            39 => 
            array (
                'id' => 41,
                'data_type_id' => 6,
                'field' => 'nome',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            40 => 
            array (
                'id' => 42,
                'data_type_id' => 6,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            41 => 
            array (
                'id' => 43,
                'data_type_id' => 6,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            42 => 
            array (
                'id' => 44,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            43 => 
            array (
                'id' => 45,
                'data_type_id' => 7,
                'field' => 'nome',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            44 => 
            array (
                'id' => 46,
                'data_type_id' => 7,
                'field' => 'matricula',
                'type' => 'text',
                'display_name' => 'Matricula',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            45 => 
            array (
                'id' => 47,
                'data_type_id' => 7,
                'field' => 'id_curso',
                'type' => 'text',
                'display_name' => 'Id Curso',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            46 => 
            array (
                'id' => 48,
                'data_type_id' => 7,
                'field' => 'CR',
                'type' => 'text',
                'display_name' => 'CR',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            47 => 
            array (
                'id' => 49,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            48 => 
            array (
                'id' => 50,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            49 => 
            array (
                'id' => 51,
                'data_type_id' => 7,
                'field' => 'aluno_belongsto_curso_relationship',
                'type' => 'relationship',
                'display_name' => 'Curso',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Curso","table":"cursos","type":"belongsTo","column":"id_curso","key":"id","label":"nome","pivot_table":"alunos","pivot":"0","taggable":"0"}',
                'order' => 4,
            ),
            50 => 
            array (
                'id' => 52,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            51 => 
            array (
                'id' => 53,
                'data_type_id' => 8,
                'field' => 'id_cursos',
                'type' => 'text',
                'display_name' => 'Id Cursos',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            52 => 
            array (
                'id' => 54,
                'data_type_id' => 8,
                'field' => 'nome',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            53 => 
            array (
                'id' => 55,
                'data_type_id' => 8,
                'field' => 'semestre',
                'type' => 'number',
                'display_name' => 'Semestre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            54 => 
            array (
                'id' => 56,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            55 => 
            array (
                'id' => 57,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            56 => 
            array (
                'id' => 58,
                'data_type_id' => 8,
                'field' => 'disciplina_curso_belongsto_curso_relationship',
                'type' => 'relationship',
                'display_name' => 'cursos',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Curso","table":"cursos","type":"belongsTo","column":"id_cursos","key":"id","label":"nome","pivot_table":"alunos","pivot":"0","taggable":"0"}',
                'order' => 3,
            ),
            57 => 
            array (
                'id' => 70,
                'data_type_id' => 7,
                'field' => 'aluno_hasmany_registro_relationship',
                'type' => 'relationship',
                'display_name' => 'Registros',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Registro","table":"registros","type":"hasMany","column":"id_alunos","key":"id","label":"id","pivot_table":"alunos","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            58 => 
            array (
                'id' => 71,
                'data_type_id' => 9,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            59 => 
            array (
                'id' => 72,
                'data_type_id' => 9,
                'field' => 'edital',
                'type' => 'text',
                'display_name' => 'Edital',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            60 => 
            array (
                'id' => 73,
                'data_type_id' => 9,
                'field' => 'descricao',
                'type' => 'text',
                'display_name' => 'Descricao',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            61 => 
            array (
                'id' => 74,
                'data_type_id' => 9,
                'field' => 'user_id',
                'type' => 'number',
                'display_name' => 'Usuário',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            62 => 
            array (
                'id' => 75,
                'data_type_id' => 9,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            63 => 
            array (
                'id' => 76,
                'data_type_id' => 9,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            64 => 
            array (
                'id' => 77,
                'data_type_id' => 9,
                'field' => 'processo_seletivo_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Usuário',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"name","pivot_table":"alunos","pivot":"0","taggable":"0"}',
                'order' => 5,
            ),
            65 => 
            array (
                'id' => 78,
                'data_type_id' => 10,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            66 => 
            array (
                'id' => 79,
                'data_type_id' => 10,
                'field' => 'sigla',
                'type' => 'text',
                'display_name' => 'Sigla',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            67 => 
            array (
                'id' => 82,
                'data_type_id' => 10,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            68 => 
            array (
                'id' => 83,
                'data_type_id' => 10,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            69 => 
            array (
                'id' => 84,
                'data_type_id' => 11,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            70 => 
            array (
                'id' => 85,
                'data_type_id' => 11,
                'field' => 'descricao',
                'type' => 'text',
                'display_name' => 'Descrição',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            71 => 
            array (
                'id' => 86,
                'data_type_id' => 11,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            72 => 
            array (
                'id' => 87,
                'data_type_id' => 11,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            73 => 
            array (
                'id' => 88,
                'data_type_id' => 12,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            74 => 
            array (
                'id' => 89,
                'data_type_id' => 12,
                'field' => 'descricao',
                'type' => 'text',
                'display_name' => 'Descricao',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            75 => 
            array (
                'id' => 90,
                'data_type_id' => 12,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            76 => 
            array (
                'id' => 91,
                'data_type_id' => 12,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            77 => 
            array (
                'id' => 92,
                'data_type_id' => 10,
                'field' => 'cota_matricula_belongstomany_documento_matricula_relationship',
                'type' => 'relationship',
                'display_name' => 'Documentos',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"\\\\App\\\\DocumentoMatricula","table":"documento_matriculas","type":"belongsToMany","column":"id","key":"id","label":"descricao","pivot_table":"cota_documento","pivot":"1","taggable":"on"}',
                'order' => 3,
            ),
            78 => 
            array (
                'id' => 93,
                'data_type_id' => 10,
                'field' => 'analise_renda',
                'type' => 'checkbox',
                'display_name' => 'Analise Renda',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Sim","off":"N\\u00e3o"}',
                'order' => 3,
            ),
            79 => 
            array (
                'id' => 94,
                'data_type_id' => 11,
                'field' => 'padrao_matriculado',
                'type' => 'checkbox',
                'display_name' => 'Padrao Matriculado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Sim","off":"N\\u00e3o","display":{"width":"4"}}',
                'order' => 3,
            ),
            80 => 
            array (
                'id' => 95,
                'data_type_id' => 11,
                'field' => 'padrao_analise',
                'type' => 'checkbox',
                'display_name' => 'Padrao Analise',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Sim","off":"N\\u00e3o","display":{"width":"4"}}',
                'order' => 4,
            ),
            81 => 
            array (
                'id' => 96,
                'data_type_id' => 11,
                'field' => 'padrao_reclassificacao',
                'type' => 'checkbox',
                'display_name' => 'Padrao Reclassificacao',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Sim","off":"N\\u00e3o","display":{"width":"4"}}',
                'order' => 5,
            ),
            82 => 
            array (
                'id' => 97,
                'data_type_id' => 13,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            83 => 
            array (
                'id' => 98,
                'data_type_id' => 13,
                'field' => 'nome',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            84 => 
            array (
                'id' => 99,
                'data_type_id' => 13,
                'field' => 'pontuacao',
                'type' => 'number',
                'display_name' => 'Pontuacao',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 12,
            ),
            85 => 
            array (
                'id' => 100,
                'data_type_id' => 13,
                'field' => 'cota_candidato',
                'type' => 'text',
                'display_name' => 'Cota Candidato',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            86 => 
            array (
                'id' => 101,
                'data_type_id' => 13,
                'field' => 'cota_ingresso',
                'type' => 'text',
                'display_name' => 'Cota Ingresso',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            87 => 
            array (
                'id' => 102,
                'data_type_id' => 13,
                'field' => 'chamada',
                'type' => 'number',
                'display_name' => 'Chamada',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 13,
            ),
            88 => 
            array (
                'id' => 103,
                'data_type_id' => 13,
                'field' => 'status_matricula_id',
                'type' => 'number',
                'display_name' => 'Status Matricula Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ),
            89 => 
            array (
                'id' => 104,
                'data_type_id' => 13,
                'field' => 'observacao',
                'type' => 'text',
                'display_name' => 'Observacao',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 14,
            ),
            90 => 
            array (
                'id' => 105,
                'data_type_id' => 13,
                'field' => 'classificacao',
                'type' => 'number',
                'display_name' => 'Classificacao',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 15,
            ),
            91 => 
            array (
                'id' => 106,
                'data_type_id' => 13,
                'field' => 'cpf',
                'type' => 'text',
                'display_name' => 'Cpf',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 16,
            ),
            92 => 
            array (
                'id' => 107,
                'data_type_id' => 13,
                'field' => 'curso_id',
                'type' => 'number',
                'display_name' => 'Curso Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            93 => 
            array (
                'id' => 108,
                'data_type_id' => 13,
                'field' => 'periodo',
                'type' => 'text',
                'display_name' => 'Periodo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            94 => 
            array (
                'id' => 109,
                'data_type_id' => 13,
                'field' => 'telefone',
                'type' => 'text',
                'display_name' => 'Telefone',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 18,
            ),
            95 => 
            array (
                'id' => 110,
                'data_type_id' => 13,
                'field' => 'celular',
                'type' => 'text',
                'display_name' => 'Celular',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 19,
            ),
            96 => 
            array (
                'id' => 111,
                'data_type_id' => 13,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 17,
            ),
            97 => 
            array (
                'id' => 112,
                'data_type_id' => 13,
                'field' => 'user_id',
                'type' => 'number',
                'display_name' => 'User Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 21,
            ),
            98 => 
            array (
                'id' => 113,
                'data_type_id' => 13,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 22,
            ),
            99 => 
            array (
                'id' => 114,
                'data_type_id' => 13,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 23,
            ),
            100 => 
            array (
                'id' => 115,
                'data_type_id' => 13,
                'field' => 'candidato_belongsto_cota_matricula_relationship',
                'type' => 'relationship',
                'display_name' => 'Cota Candidato',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\CotaMatricula","table":"cota_matriculas","type":"belongsTo","column":"cota_candidato","key":"id","label":"sigla","pivot_table":"alunos","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            101 => 
            array (
                'id' => 116,
                'data_type_id' => 13,
                'field' => 'candidato_belongsto_cota_matricula_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Cota Ingresso',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\CotaMatricula","table":"cota_matriculas","type":"belongsTo","column":"cota_ingresso","key":"id","label":"sigla","pivot_table":"alunos","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            102 => 
            array (
                'id' => 117,
                'data_type_id' => 13,
                'field' => 'candidato_belongsto_curso_relationship',
                'type' => 'relationship',
                'display_name' => 'Curso',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Curso","table":"cursos","type":"belongsTo","column":"curso_id","key":"id","label":"nome","pivot_table":"alunos","pivot":"0","taggable":"0"}',
                'order' => 3,
            ),
            103 => 
            array (
                'id' => 118,
                'data_type_id' => 13,
                'field' => 'candidato_belongsto_status_matricula_relationship',
                'type' => 'relationship',
                'display_name' => 'Status',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\StatusMatricula","table":"status_matriculas","type":"belongsTo","column":"status_matricula_id","key":"id","label":"descricao","pivot_table":"alunos","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            104 => 
            array (
                'id' => 119,
                'data_type_id' => 13,
                'field' => 'candidato_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Servidor',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"name","pivot_table":"alunos","pivot":"0","taggable":"0"}',
                'order' => 20,
            ),
            105 => 
            array (
                'id' => 120,
                'data_type_id' => 8,
                'field' => 'carga_horaria',
                'type' => 'number',
                'display_name' => 'Carga Horária',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            106 => 
            array (
                'id' => 121,
                'data_type_id' => 7,
                'field' => 'registro_situacao_id',
                'type' => 'number',
                'display_name' => 'Registro Situacao Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
        ));
        
        
    }
}