<?php

use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null}',
                'created_at' => '2018-05-19 19:20:03',
                'updated_at' => '2018-05-20 21:21:26',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2018-05-19 19:20:03',
                'updated_at' => '2018-05-19 19:20:03',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2018-05-19 19:20:04',
                'updated_at' => '2018-05-19 19:20:04',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'passivos',
                'slug' => 'passivos',
                'display_name_singular' => 'Passivo',
                'display_name_plural' => 'Passivos',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Passivo',
                'policy_name' => NULL,
                'controller' => 'PassivoController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null}',
                'created_at' => '2018-05-21 05:31:07',
                'updated_at' => '2018-05-23 00:39:34',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'mensagens',
                'slug' => 'mensagens',
                'display_name_singular' => 'Mensagen',
                'display_name_plural' => 'Mensagens',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Mensagem',
                'policy_name' => NULL,
                'controller' => 'MensagemController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null}',
                'created_at' => '2018-05-27 06:47:43',
                'updated_at' => '2018-05-27 06:47:43',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'cursos',
                'slug' => 'cursos',
                'display_name_singular' => 'Curso',
                'display_name_plural' => 'Cursos',
                'icon' => 'voyager-company',
                'model_name' => 'App\\Models\\Curso',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null}',
                'created_at' => '2018-07-09 12:22:53',
                'updated_at' => '2018-07-09 12:22:53',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'alunos',
                'slug' => 'alunos',
                'display_name_singular' => 'Aluno',
                'display_name_plural' => 'Alunos',
                'icon' => 'voyager-person',
                'model_name' => 'App\\Models\\Aluno',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null}',
                'created_at' => '2018-07-09 12:23:17',
                'updated_at' => '2018-07-09 20:13:37',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'disciplina_cursos',
                'slug' => 'disciplina-cursos',
                'display_name_singular' => 'Disciplina Curso',
                'display_name_plural' => 'Disciplina Cursos',
                'icon' => 'voyager-file-text',
                'model_name' => 'App\\Models\\DisciplinaCurso',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null}',
                'created_at' => '2018-07-09 12:26:49',
                'updated_at' => '2018-07-09 18:41:21',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'processo_seletivos',
                'slug' => 'processo-seletivos',
                'display_name_singular' => 'Processo Seletivo',
                'display_name_plural' => 'Processo Seletivos',
                'icon' => 'voyager-calendar',
                'model_name' => 'App\\Models\\ProcessoSeletivo',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null}',
                'created_at' => '2018-12-03 23:27:01',
                'updated_at' => '2018-12-03 23:27:58',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'cota_matriculas',
                'slug' => 'cota-matriculas',
                'display_name_singular' => 'Cota Matricula',
                'display_name_plural' => 'Cota Matriculas',
                'icon' => 'voyager-wallet',
                'model_name' => 'App\\Models\\CotaMatricula',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null}',
                'created_at' => '2019-01-11 01:26:15',
                'updated_at' => '2019-01-14 03:10:14',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'status_matriculas',
                'slug' => 'status-matriculas',
                'display_name_singular' => 'Status Matricula',
                'display_name_plural' => 'Status Matriculas',
                'icon' => 'voyager-params',
                'model_name' => 'App\\Models\\StatusMatricula',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-11 01:27:02',
                'updated_at' => '2019-01-16 08:38:05',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'documento_matriculas',
                'slug' => 'documento-matriculas',
                'display_name_singular' => 'Documento Matricula',
                'display_name_plural' => 'Documento Matriculas',
                'icon' => NULL,
                'model_name' => 'App\\Models\\DocumentoMatricula',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-12 15:13:13',
                'updated_at' => '2019-01-14 03:37:06',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'candidatos',
                'slug' => 'candidatos',
                'display_name_singular' => 'Candidato',
                'display_name_plural' => 'Candidatos',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Candidato',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":"nome"}',
                'created_at' => '2019-01-21 23:27:54',
                'updated_at' => '2019-01-21 23:39:42',
            ),
        ));
        
        
    }
}